// Example JavaScript loader for Ashen Guild processed sprite frames.
// Works with the filename convention generated by tools/ashen_asset_pipeline.py.

const DIRECTIONS = ["north", "south", "east", "west"];

const ANIMATIONS = {
  idle: 4,
  walk: 6,
  attack: 4,
};

function framePath(baseDir, character, direction, animation, frameNumber) {
  const n = String(frameNumber).padStart(2, "0");
  return `${baseDir}/${character}_${direction}_${animation}_${n}.png`;
}

export async function loadCharacterAnimations(baseDir, character) {
  const animations = {};

  for (const direction of DIRECTIONS) {
    animations[direction] = {};

    for (const [animation, count] of Object.entries(ANIMATIONS)) {
      animations[direction][animation] = [];

      for (let i = 1; i <= count; i++) {
        const img = new Image();
        img.src = framePath(baseDir, character, direction, animation, i);
        animations[direction][animation].push(img);
      }
    }
  }

  return animations;
}

// Example usage:
// const warrior = await loadCharacterAnimations(
//   "assets_processed/characters/warrior",
//   "warrior"
// );
//
// Draw frame:
// ctx.drawImage(warrior.south.idle[0], x, y);
