extends Node

# Example Godot loader for processed Ashen Guild character frames.
# Filename convention generated by tools/ashen_asset_pipeline.py:
# warrior_south_walk_01.png

const DIRECTIONS := ["north", "south", "east", "west"]
const ANIMATIONS := {
	"idle": 4,
	"walk": 6,
	"attack": 4,
}

func load_character_animations(base_dir: String, character: String) -> Dictionary:
	var result := {}

	for direction in DIRECTIONS:
		result[direction] = {}

		for animation in ANIMATIONS.keys():
			result[direction][animation] = []
			var frame_count: int = ANIMATIONS[animation]

			for i in range(1, frame_count + 1):
				var frame_number := str(i).pad_zeros(2)
				var path := "%s/%s_%s_%s_%s.png" % [base_dir, character, direction, animation, frame_number]
				var texture := load(path)
				result[direction][animation].append(texture)

	return result

# Example usage:
# var warrior = load_character_animations(
#     "res://assets_processed/characters/warrior",
#     "warrior"
# )
#
# $Sprite2D.texture = warrior["south"]["idle"][0]
